name: Release

on:
  create:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Version must be matched
        run: |
          if [ ! ${{ github.ref_name }} = v$(npm pkg get version | tr -d '"') ]
          then exit 1
          fi

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
